### ISSUE TITLE
RFC 1918 matches on values that do not meet the specifications

### ISSUE THREAD

**Issue by mobiusKey** [BishopFox/GitGot#13]
**Description**
The regex for the RFC 1918 checks will match values that do not meet the RFC 1918 specifications

**Steps Taken**
Running a normal behavior

**Expected behavior**
Match on internal IP addresses and ignore values that do not meet the specifications

**Example Value**
The current regex will match the value 10.234222222 which is not a legitimate internal IP address

**Fix**
This issue can be fixed by replacing the regex in default.list with this

127\.(([0-9]){1,3}\.){2}([0-9]){1,3}|10\.(([0-9]){1,3}\.){2}[0-9]{1,3}|172\.[123][0-9]\.([0-9\.]{1,3}){2}|192\.168\.([0-9]{1,3}\.[0-9]{1,3})

please change the regex so that GitGot does not create unnecessary false positives

**Comment by the-bumble** [comment]
Thank you for reporting this! I tried reaching out to you on your PR, but you must've gotten busy. Fixed by 915c37ed6800889b76d0e32b2db7d6f558707d5a
