### ISSUE TITLE
Input list of subdomains

### ISSUE THREAD

**Issue by ghost** [BishopFox/GitGot#2]
Provide option to query a list of subdomains

**Comment by the-bumble** [comment]
Hey @dtnml!

Good news! You can already do this via GitHub search syntax.
`./gitgot.py -q "subdomain-a.example.com|subdomain-b.example.com"`

Or, from a file:
`./gitgot.py -q "$(paste -sd '|' subdomains)"`

The query parameter uses the GitHub API on the backend so all GitHub search operators can be used in the query.

See:

- https://github.com/BishopFox/GitGot#query-syntax

Hope that helps!
