### ISSUE TITLE
AttributeError: property 'value' of '_ValuedAttribute' object has no setter

### ISSUE THREAD

**Issue by Fusion3301** [BishopFox/GitGot#29]
Hello,
I generated GIT PUBLIC TOKEN and copied it to its desired location. But I am encountering "AttributeError: property 'value' of '_ValuedAttribute' object has no setter" Error again and again. 
Please help me troubleshooting this issue.
![image](https://github.com/BishopFox/GitGot/assets/137278311/3b0cf910-633c-4769-adc1-ecd5e14bb62e)

**Comment by cedelgadosalazar** [comment]
same here

![image](https://github.com/BishopFox/GitGot/assets/84478668/8d22d36a-aabb-48ad-a7f4-e97dd8e4fec7)

I even tried on an old kali version (2022) and the result is the same.

**Comment by mox-folder** [comment]
This issue is fixed in https://github.com/BishopFox/GitGot/commit/4ce0d88a36c285a7ceaca84104009a8e3b6f6e99.

**Comment by mox-folder** [comment]
Fixed in https://github.com/BishopFox/GitGot/commit/4ce0d88a36c285a7ceaca84104009a8e3b6f6e99
