### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Willies31** [BishopFox/GitGot#8]
Hello and thank you for this great tool. 

I am using a Windows 10 system and when installing the tool through the REQUIREMENTS.TXT I get the following errors, any idea?

![image](https://user-images.githubusercontent.com/48537020/61557829-4473bb00-aa33-11e9-8c22-0d29c0a77e4d.png)

**Comment by the-bumble** [comment]
Hi Willies31,

I'm not a Windows user, but based on the error message it looks like you are missing Microsoft Visual C++. 

Best of luck!

**Comment by anon3engineer** [comment]
root@kali:~# apt-get install libfuzzy-dev ssdeep
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libfuzzy-dev
E: Unable to locate package ssdeep



Please help me with this issue.. :(

**Comment by the-bumble** [comment]
We'll be adding Docker support soon for those having difficulty installing dependencies.

**Comment by the-bumble** [comment]
Hi Willies31 and anon3engineer,

Try the new Docker installation instructions in the README. Hopefully that helps simplifies installation and usage :)

Thank you!
